# Generated by Django 4.1.7 on 2023-04-02 17:10

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen_portada',
            field=models.ImageField(blank=True, default='default-image.jpg', null=True, upload_to=''),
        ),
    ]
